RaceDayDisplayApp/Models/Meeting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RaceDayDisplayApp.Models
{
    public class MeetingBase
    {
        [Key]
        [CustomDisplay(DisplayOn.NONE)]
        public int MeetingId { get; set; }

        [CustomDisplay(DisplayOn.NONE)]
        public DateTime MeetingDate { get; set; }

        [Display(Name = "Date", Order = 1)]
        [CustomDisplay(DisplayOn.ALL)]
        public string _MeetingDate { get { return MeetingDate.ToString(@"ddd MMM d\t\h yyyy"); } }
        
        [CustomDisplay(DisplayOn.NONE)]
        public DateTime MinRaceJumpDateTimeUTC { get; set; }

        [CustomDisplay(DisplayOn.NONE)]
        public TimeSpan MinJumpTimeLocal { get; set; }

        [Display(Name = "Venue", Order = 2)]
        [CustomDisplay(DisplayOn.ALL)]
        public string RaceCourseName { get; set; }
    }

    public class Meeting : MeetingBase
    {
        [CustomDisplay(DisplayOn.NONE)]
        public int supermeetingtypeid { get; set; }

        [CustomDisplay(DisplayOn.NONE)]
        public int RaceCourseId { get; set; }

        [CustomDisplay(DisplayOn.NONE)]
        public int CountryId { get; set; }

        [CustomDisplay(DisplayOn.NONE)]
        public string CountryCode { get; set; }

        //[Display(Name = "Weather", Order = 0)]
        //[CustomDisplay(DisplayOn.BOTH)]
        //public string WeatherName { get; set; }

        //[Display(Name = "Going", Order = 0)]
        //[CustomDisplay(DisplayOn.BOTH)]
        //public string DefaultGoingName { get; set; }

        [Display(Name = "No./Races", Order = 3)]
        [CustomDisplay(DisplayOn.ALL)]
        public int NumberOfRaces { get; set; }

        //[CustomDisplay(DisplayOn.NONE)]
        //public string MeetingCode { get; set; }

        [Display(Name = "Time of Day", Order = 4)]
        [CustomDisplay(DisplayOn.HK)]
        public bool HK_isNightMeet { get; set; }

        //[Display(Name = "Time of Day", Order = 0)]
        //[CustomDisplay(DisplayOn.BOTH)]
        //public string TimeOfDay { get; set; }

        [Display(Name = "Track Variant", Order = 5)]
        [CustomDisplay(DisplayOn.ALL)]
        public string CourseVariantName { get; set; }
        
        //public string Code { get; set; }
        //public bool InUse { get; set; }
        //public DateTime SeasonStart { get; set; }

        [CustomDisplay(DisplayOn.NONE)]
        public IList<RaceBase> Races { get; set; }


        [CustomDisplay(DisplayOn.NONE)]
        public CountryEnum CountryEnum
        {
            get { return Country.GetEnum(CountryCode); }
        }

        //[CustomDisplay(DisplayOn.NONE)]
        //public static Meeting DummyMeeting
        //{
        //    get
        //    {
        //        Random rdm = new Random();
        //        Meeting m = FizzWare.NBuilder.Builder<Meeting>.CreateNew().Build();
        //        m.Races = FizzWare.NBuilder.Builder<RaceBase>.CreateListOfSize(rdm.Next(10) + 1).Build();

        //        return m;
        //    }
        //}
    }

}

RaceDayDisplayApp/Models/_Helpers/RunnerHistoryHelper.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Xml.Linq;
using System.Linq;

namespace RaceDayDisplayApp.Models
{
    public static class RunnerHistoryHelper
    {
        public static string[] ControlFields = new[] { "Season" };//,  "SwampedLast?", "FU", "LU" };

        static Dictionary<string, string> alwaysVisibleGroups = new Dictionary<string,string>();
        static Dictionary<KeyValuePair<string, string>, List<string>> fields;
        static Dictionary<string, string> formatters;

        static RunnerHistoryHelper()
        {
            loadConfigFile();
        }

        private static void loadConfigFile()
        {
            fields = new Dictionary<KeyValuePair<string, string>, List<string>>();
            formatters = new Dictionary<string, string>();

            XDocument doc = XDocument.Load(AppDomain.CurrentDomain.BaseDirectory + "RunnerHistoryFields.config");
            doc.Root.Elements("group").ToList().ForEach(g =>
                {
                    string name = "", value = "", countryCode = "";
                    try
                    {
                        name = (string)g.Attribute("name").Value;
                        if (g.Attribute("countrycode") != null)
                            countryCode = (string)g.Attribute("countrycode").Value;

                        var groupFields = new List<string>();
                        g.Elements("field").ToList().ForEach(f =>
                            {
                                value = f.Value;
                                if (f.Attribute("formatter") != null && !formatters.ContainsKey(value))
                                    formatters.Add(value, f.Attribute("formatter").Value);

                                groupFields.Add(value);
                            });

                        fields.Add(new KeyValuePair<string, string>(countryCode, name), groupFields);

                        if (bool.Parse(g.Attribute("alwaysVisible").Value))
                            alwaysVisibleGroups[countryCode] = name;
                    }
                    catch (Exception e)
                    {
                        throw new Exception("Error parsing RunnerHistoryFields.xml - group=" + name + " country=" + countryCode + " value=" + value, e);
                    }
                });
        }

        /// <summary>
        /// Used at view level to format fields before displaying them
        /// </summary>
        public static string FormatField(string name, object value)
        {
            if (value == null)
                return null;

            string formatter;
            if (formatters.TryGetValue(name, out formatter))
            {
                string val;
                switch (formatter)
	            {
                    case "onlyDate":
                        val = ((DateTime)value).ToShortDateString();
                        break;
                    case "onlySecs":
                        var aux = (TimeSpan)value;
                        val = string.Format("{0}.{1}", aux.Seconds, aux.Milliseconds / 10);
                        break;
                    //case "oneDigit":
                    //    val = ((float)value).ToString("0.0");
                    //    break;
                    default:
                        val = value.ToString();
                    break;
	            }
                return val;
            }
            return value.ToString();
        }

        /// <summary>
        /// Used on the Runner History page to render group buttons based on the config file. 
        /// The view will use the result to render buttons this way:
        /// <input id="btn_@(i)" class="btn_hist" type="button" value="@(item.Key)" onclick="showFields(@(i++), @(item.Value))" />
        /// </summary>
        internal static Dictionary<string,string> GetFieldsIndexes(string countryCode, dynamic runnerHistoryItem)
        {
            var groups = new Dictionary<string, List<int>>();

            var countryFields = fields.Where(f => f.Key.Key == "" || f.Key.Key == countryCode).ToList();            
            countryFields.ForEach(f => groups.Add(f.Key.Value, new List<int>(f.Value.Count())));

            int i=1;
            foreach (KeyValuePair<string, object> kvp in runnerHistoryItem)
            {
                if (!ControlFields.Contains(kvp.Key))
                {
                    foreach (var f in countryFields)
                    {
                        if (f.Value.Contains(kvp.Key))
                            groups[f.Key.Value].Add(i);
                    }
                    i++;
                }
            }

            var result = new Dictionary<string, string>();
            groups.ToList().ForEach(g => 
                {
                    var aux = g.Value;
                    string fixedGroup;
                    //add country-specific fixed fields
                    if (alwaysVisibleGroups.TryGetValue(countryCode, out fixedGroup) && g.Key != fixedGroup)
                        aux.AddRange(groups[fixedGroup]);
                    //add country-independent fixed fields
                    if (alwaysVisibleGroups.TryGetValue("", out fixedGroup) && g.Key != fixedGroup)
                        aux.AddRange(groups[fixedGroup]);
                    
                    result.Add(g.Key, "['" + string.Join("','", aux) + "']");
                });

            return result;
        }

        /// <summary>
        /// Just returns the number of DISPLAY attributes for Runners. It is used by the view to calculate the colspan on the html table
        /// </summary>
        public static int GetNumAttrs(dynamic obj)
        {
            return ((IEnumerable<KeyValuePair<string, object>>)obj).Where(kvp => !ControlFields.Contains(kvp.Key)).Count();
        }
    }
}

RaceDayDisplayApp/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RaceDayDisplayApp.Models;
using MvcJqGrid;
using System.Configuration;
using RaceDayDisplayApp.Filters;
using RaceDayDisplayApp.DAL;
using System.Dynamic;
using RaceDayDisplayApp.Common;

namespace RaceDayDisplayApp.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class MeetingsController : Controller
    {
        private DBGateway entities = new DBGateway();


        public ActionResult Index()
        {
            if (User.IsInRole(ConfigValues.FullAccessRole))
                return View();
            else
                return RedirectToAction("RaceList");
        }

        //
        // GET: /Meetings/

        public ActionResult MeetingList(bool today = true)
        {
            ViewBag.Today = today;
            return View(entities.GetCountries(today));
        }

        public ActionResult RaceList(bool today = true)
        {
            ViewBag.Today = today;
            return View(entities.GetRacesList(today));
        }

        //
        // GET: /Meetings/Details/5

        public ActionResult Details(int id = 0)
        {
            //get the meeting info
            Meeting meeting = entities.GetMeeting(id);
            if (meeting == null)
            {
                return HttpNotFound();
            }

            //get the user settings
            var userId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
            //ViewBag.UserSettings = entities.GetUserSettings(userId, meeting.CountryEnum);

            //to render or not the statistics sections
            ViewBag.FullAccess = User.IsInRole(ConfigValues.FullAccessRole);

            return View(meeting);
        }

        public ActionResult RaceDetails(int id, CountryEnum country, bool today = true)
        {
            //get the meeting and Race info
            Meeting meeting = entities.GetMeetingByRaceId(id);
            if (meeting == null)
            {
                return HttpNotFound();
            }

            meeting.Races = new List<RaceBase>(new[] { RacesCache.Instance.GetRace(id, country) });

            //set previous and next race in the sequence
            var racesList = entities.GetRacesList(today).ToList();
            var index = racesList.FindIndex(r => r.RaceId == id);
            ViewBag.Previous = index > 0 ? racesList[index - 1] : null;
            ViewBag.Next = index + 1 < racesList.Count() ? racesList[index + 1] : null;
            ViewBag.Today = today;

            //get the user settings
            var userId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
            //ViewBag.UserSettings = entities.GetUserSettings(userId, meeting.CountryEnum);

            //columns to display for this race
            ViewBag.GridColumns = ModelHelper.GetGridColumns(meeting.Races[0] as Race);

            //to render or not the statistics sections
            ViewBag.FullAccess = User.IsInRole(ConfigValues.FullAccessRole);

            return View(meeting);
        }

        public ActionResult Race(int id, CountryEnum country)
        {
            var r = RacesCache.Instance.GetRace(id, country);
            if (r == null)
            {
                return HttpNotFound();
            }

            ViewBag.GridColumns = ModelHelper.GetGridColumns(r);
            return View("_Race", r);
        }

        /// <summary>
        /// Called async by the jqGrid on details view
        /// </summary>
        /// <returns>A list of runners</returns>
        public ActionResult GridData(int id, CountryEnum country, GridSettings gridSettings)
        {
            var race = RacesCache.Instance.GetRace(id, country);
            var runners = race.Runners;

            if (runners == null)
            {
                return  null;
            }

            if (runners.Count() > 0)
            {
                //runners.First().isDone; //for testing purposes

                //sorting
                if (gridSettings.SortColumn != "")
                {
                    //TODO this does not work
                    if (gridSettings.SortOrder == "asc")
                        runners = runners.OrderBy(o => ((IEnumerable<KeyValuePair<string, object>>)o).First(kvp => kvp.Key == gridSettings.SortColumn).Value).ToList();
                        //runners = runners.OrderBy(o => o.GetType().GetProperty(gridSettings.SortColumn).GetValue(o, null)).ToList();
                    else
                        runners = runners.OrderByDescending(o => ((IEnumerable<KeyValuePair<string, object>>)o).First(kvp => kvp.Key == gridSettings.SortColumn).Value).ToList();
                        //runners = runners.OrderByDescending(o => typeof(Runner).GetProperty(gridSettings.SortColumn).GetValue(o)).ToList();
                }
                else
                    runners = runners.OrderBy(o => o.HorseNumber).ToList(); //default sorting criteria
            }
            
            var now = DateTime.UtcNow;
            var jsonData = new
            {
                total = runners.Count(),
                page = gridSettings.PageIndex,
                records = runners.Count(),
                rows = runners,
                race = race.GetLightCopy(),
                dbUpdatedSecs = race.RefreshValues.LastDBUpdate == default (DateTime) ? -1 :
                                (now - race.RefreshValues.LastDBUpdate).TotalSeconds,
                serverUpdatedSecs = (now - race.RefreshValues.LastServerRefresh).TotalSeconds,
                //add delay to avoid waiting in the lock
                nextRefreshSecs = race.isDone ? -1 : 
                        (race.RefreshValues.NextRefresh - now).TotalSeconds + ConfigValues.ClientAddedDelay 
            };

            JsonNetResult jsonNetResult = new JsonNetResult();
            jsonNetResult.Formatting = Newtonsoft.Json.Formatting.Indented;
            jsonNetResult.Data = jsonData;
            return jsonNetResult;
        }

        //public ActionResult GridSettings(CountryEnum country)
        //{
        //    //get the user settings
        //    var userId = WebMatrix.WebData.WebSecurity.GetUserId(User.Identity.Name);
        //    var settings = entities.GetUserSettings(userId, country);

        //    return View("_GridSettings", settings);
        //}

        public ActionResult RunnerHistory(int id, string countryCode)
        {
            dynamic model = new ExpandoObject();
            model.HorseDetails = entities.GetHorseDetailsData(id);

            var runnerHistory = entities.GetRunnerHistory(id, countryCode);
            model.RunnerHistory = runnerHistory;
            model.Fields = RunnerHistoryHelper.GetFieldsIndexes(countryCode, runnerHistory.First());

            return View(model);
        }

    }
}

RaceDayDisplayApp/Controllers/RaceResearchController.cs
using RaceDayDisplayApp.Common;
using RaceDayDisplayApp.DAL;
using RaceDayDisplayApp.Filters;
using RaceDayDisplayApp.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RaceDayDisplayApp.Controllers
{
    [Authorize(Roles = ConfigValues.FullAccessRole)]
    //[Authorize]
    [InitializeSimpleMembership]
    public class RaceResearchController : Controller
    {
        private DBGateway entities = new DBGateway();

        //
        // GET: /RunnerHistory/

        public ActionResult Index()
        {
            var filters = entities.GetHistoryFilters();
            return View(filters);
        }

        //public ActionResult Tables(int country, int racecourse, int season,
        //                           int meetType, int raceType, int noRunners)
        public ActionResult Tables(HistoryFilters filters)
        {
            if (ModelState.IsValid)
            {
                var result = new RaceResearchViewModel();
                result.MarketData = entities.GetMarketData(filters, 0);
                result.FormFactors = entities.GetFormFactors(filters);
                return View("_Tables", result);
            }
            return null;
        }

        public ActionResult StatsTable(HistoryFilters filters)
        {
            return View("_StatsTable", entities.GetMarketData(filters, ConfigValues.MaxStatisticsResults));
        }
    }
}

RaceDayDisplayApp/Views/Meetings/Details.cshtml
@using RaceDayDisplayApp.Models

@model RaceDayDisplayApp.Models.Meeting

@{
    ViewBag.Title = "Meeting Details";
}

@section scripts
{
    @Scripts.Render("~/bundles/jqGrid")
}

@Html.HiddenFor(m => m.CountryEnum)
@Html.HiddenFor(m => m.CountryCode)


<div class="main_container">
    <div id="top_panel">
        @*<div id="panel_left">*@
            <h2>Meeting Details</h2>

            <div class="select">
                <div class="select_div">
                    @Html.DropDownList("RacesList", new SelectList(Model.Races, "RaceId", "RaceNumber"), "Race number")
                </div>
                <div class="select_div" id="btns_div">
                    <div class="btn_container">
                        <input id="btn_refresh" type="button" value="Refresh" onclick="refreshGrid()" />
                    </div>
                    <div class="btn_container">
                        <input id="btn_default" type="button" value="Default" onclick="defaultSettings()" />
                    </div>
                </div>
            </div>
            <div id="meeting_details">
                @{Html.RenderPartial("_MeetingData", Model);}
            </div>
            <div id="race_details">
            </div>
            @*<div id="chks_container" class="chks_container">
                @{Html.RenderPartial("_GridSettings", (IEnumerable<ViewUserSetting>)ViewBag.UserSettings);}
            </div>*@
        @*</div>
        <div id="panel_right">
            <h2>Chart Details</h2>
            <p>Drag & Drop grid items to this area</p>
        </div>*@
    </div>
    <div id="form-box"></div>
</div>

RaceDayDisplayApp/Views/Meetings/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>*@

<div class="index_buttons">
    <form action="/Meetings" method="get">
        <input class="buttons" id="Button1" type="submit" value="Upcoming Races" />
    </form>
    <form action="/RaceResearch" method="get">
        <input class="buttons" id="Button2" type="submit" value="Race Research" />
    </form>
</div>

RaceDayDisplayApp/Views/Meetings/MeetingList.cshtml
@model IEnumerable<RaceDayDisplayApp.Models.Country>

@{
    ViewBag.Title = ViewBag.Today? "Upcoming Meetings" : "All meetings";
}

<div class="index_head">
    @if (ViewBag.Today)
    {
        <h2>@String.Format("Upcoming Meetings starting {0}, {1}", DateTime.Today.DayOfWeek.ToString(), DateTime.Today.ToShortDateString())</h2>
        <div class="index_link1">
            @Html.ActionLink("View Upcoming Meetings", "MeetingList", new { today = false })
        </div>
    }
    else
    {
        <h2>All Meetings</h2>
        <div class="index_link1">
            @Html.ActionLink("View only upcoming Meetings", "MeetingList", new { today = true })
        </div>
    }
    <div class="index_link2">
        @Html.ActionLink("Change to Races view", "RaceList")
    </div>
</div>

<div class="countries_list">
    @foreach (var country in Model)
{
    <div class="boxes country">
        <h3><p>@Html.DisplayFor(modelItem => country.Name):</p></h3>

        @if (country.Meetings != null && country.Meetings.Any())
        {
            <table>
                <tr>
                    <th>Date</th>
                    <th>Local</th>
                    <th>UTC</th>
                    <th>Racecourse</th>
                </tr>
                @{ int i = 0; }
                @foreach (var meeting in country.Meetings)
                {
                    @*var linkText = string.Format("{0}{1} - {2}",
                                ViewBag.Today? "" : meeting.MeetingDate.ToShortDateString() + " - ",
                                meeting.MinRaceJumpTimeLocal.ToShortTimeString(), meeting.RaceCourseName);
                        <li>@Html.ActionLink(linkText, "Details", new { id = meeting.MeetingId })</li>*@

                    <tr>
                        <td>@meeting.MeetingDate.ToShortDateString()</td>
                        <td>@(meeting.MinJumpTimeLocal.ToString())</td>
                        <td>@(meeting.MinRaceJumpDateTimeUTC.ToShortTimeString())</td>
                        <td>@Html.ActionLink(meeting.RaceCourseName ?? "(no race course name)", "Details", new { id = meeting.MeetingId })</td>
                    </tr>

                    if (i++ > RaceDayDisplayApp.Common.ConfigValues.MeetingListLimit) { break; }

                }
            </table>
        }
    </div>
}
</div>

RaceDayDisplayApp/Views/Meetings/RaceDetails.cshtml
@using RaceDayDisplayApp.Models

@model RaceDayDisplayApp.Models.Meeting

@{
    ViewBag.Title = "Meeting Details";
}

@section scripts
{
    @Scripts.Render("~/bundles/jqGrid")
}

@Html.HiddenFor(m => m.CountryEnum)
@Html.HiddenFor(m => m.CountryCode)

<div class="main_container">
    <div id="top_panel">
        @*<div id="panel_left">*@
            <div id="nextPreviousRace" class="boxes">
                @{ var prev = ViewBag.Previous as RaceDisplay; }
                @{ var next = ViewBag.Next as RaceDisplay; }
                <div class="prev">
                    @if (prev != null)
                    {
                        @Html.ActionLink(String.Format("Previous ({0} No {1})", prev.RaceName, prev.RaceNumber),
                                     "RaceDetails", new { id = prev.RaceId, country = prev.CountryEnum, today = ViewBag.Today, @class = "boxes"});
                    }
                </div>
                <div class="next">
                    @if (next != null)
                    {
                        @Html.ActionLink(String.Format("Next ({0} No {1})", next.RaceName, next.RaceNumber),
                                          "RaceDetails", new { id = next.RaceId, country = next.CountryEnum, today = ViewBag.Today });
                    }
                </div>
            </div>
            <div class="select">
                <div class="select_div">
                    @*<h2>Race Details</h2>*@
                    <h2>@Model.RaceCourseName</h2>
                    
                </div>
                <div class="select_div visible" id="btns_div">
                    <div class="btn_container">
                        <input class="buttons" id="btn_refresh" type="button" value="Refresh" onclick="refreshGrid()" />
                    </div>
                    <div class="btn_container">
                        <input class="buttons" id="btn_default" type="button" value="Default" onclick="defaultSettings()" />
                    </div>
                </div>
            </div>
            <div class="details_container">
                <div id="meeting_details" class="boxes">
                    @{Html.RenderPartial("_MeetingData", Model);}
                </div>
                <div id="race_details" class="boxes">
                    @{Html.RenderPartial("_RaceData", Model.Races[0]);}
                </div>
            </div>
        @*<div id="chks_container" class="chks_container boxes visible">
            @{Html.RenderPartial("_GridSettings", (IEnumerable<ViewUserSetting>)ViewBag.UserSettings);}
        </div>*@
        @*</div>
        <div id="panel_right" class="visible">
            <h2>Chart Details</h2>
            <p>Drag & Drop grid items to this area</p>
        </div>*@
    </div>
    <div id="form-box">
        @{Html.RenderPartial("_GridData", Model.Races[0]);}
    </div>
</div>

RaceDayDisplayApp/Views/Meetings/_GridData.cshtml
@using RaceDayDisplayApp.Models
@using MvcJqGrid

@{
    Layout = null;
}

@model Race

@Html.HiddenFor(m => m.RaceId)


<div class="grid_buttons_div">
    @{if (Model.Runners.Count > 0)
    {
        var i = 0;
        foreach (var item in LiveDataGridHelper.GetFieldsIndexes(Model.CountryCode, Model.Runners[0]))
        {
            <div class="hist_table_controls">
                <input id="btn_@(i)" class="btn_hist" type="button" value="@(item.Key)" onclick="showFields(@(i++), @(item.Value))" />
            </div>
        }
    }
    }
</div>





<tr>
    <td width="10"><span class="cell_favorite">00</span></td>
    <td width="70" align="left">Favourite</td>
    <td width="10"><span class="cell_dropBy20">00</span></td>
    <td width="100">Odds Drop by 20%</td>
    <td width="10"><span class="cell_dropBy50">00</span></td>
    <td width="100">Odds Drop by 50%</td>
</tr>


@(Html.Grid("race_grid")
.SetDataType(MvcJqGrid.Enums.DataType.Json)
.SetHeaderTitles(true)
.OnAfterInsertRow("gridAfterInsertRow(rowid,rowdata,rowelem)")
.OnGridComplete("hideColumnsFirstTime()")
.SetAltRows(true)
.SetAltClass("alt_rows")
.AddColumns(ViewBag.GridColumns)
.SetUrl(Url.Action("GridData", "Meetings", new { id = Model.RaceId, country = Model.CountryEnum }))
//.SetUrl("Meetings/GridData/" + Model.RaceId + "?isStarted='+$('#isStarted').val()+'&isDone='+$('#isDone').val()+'")
.SetAutoWidth(true)
.SetLoadUi(MvcJqGrid.Enums.LoadUi.Block)
.SetViewRecords(true)
.SetEmptyRecords("No Runners Found")
.SetShowAllSortIcons(true)
.SetShrinkToFit(true))

<div id="refreshInfo"></div>

RaceDayDisplayApp/Views/Meetings/_MeetingData.cshtml
@using RaceDayDisplayApp.Models

@{
    Layout = null;
}

@model Meeting


<h3>Meeting Details</h3>
<div class="details_attrs">
    @foreach (var field in ModelHelper.ToNameValuePairs(Model, Model.CountryEnum))
    {
        <div class="details_attrs_wrapper">
            @field.DisplayName:
            @field.Value
        </div>
    }
</div>
@if (ViewBag.FullAccess)
{
    <div class="history-container">

    @using (Html.BeginForm("StatsTable", "RaceResearch", FormMethod.Post, new { id = "meeting-form" }))
    {
        @Html.AntiForgeryToken()

        @Html.Hidden("SelectedCountryId", Model.CountryId)
        @Html.Hidden("SelectedRaceCourseId", Model.RaceCourseId)
        @*@Html.Hidden("SelectedSeasonId", Model.SeasonId)*@ 
        @Html.Hidden("SelectedSuperMeetTypeId", Model.supermeetingtypeid)
        @*@Html.Hidden("SelectedSuperRaceTypeId", Model.SuperRaceId)*@
        @*@Html.Hidden("SelectedNumRunnersId", Model.NumberOfRunners)*@
    }

        <div class="panel-flip buttons" id="meeting-flip"><span id="meeting-span">Show</span> more (FAV/LSW/TF/QN/F4 statistics)</div>
        <div class="panel-history" id="meeting-history">
        </div>
    </div>
}

RaceDayDisplayApp/Views/Meetings/_Race.cshtml
@{
    Layout = null;
}

@model RaceDayDisplayApp.Models.Race

@{Html.RenderPartial("_RaceData", Model);}
<!--GRID STARTS HERE-->
@{Html.RenderPartial("_GridData", Model);}

RaceDayDisplayApp/Views/Meetings/_RaceData.cshtml
@using RaceDayDisplayApp.Models

@{
    Layout = null;
}

@model Race


<div class="details_attrs">
    @foreach (var field in ModelHelper.ToNameValuePairs(Model, Model.CountryEnum))
    {
        <div class="details_attrs_wrapper">
            @field.DisplayName:
            <span id="@(field.FieldName)">@(field.Value)</span>
        </div>
    }
</div>
@if (ViewBag.FullAccess)
{
    <div class="history-container">

    @using (Html.BeginForm("StatsTable", "RaceResearch", FormMethod.Post, new { id = "race-form" }))
    {
        @Html.AntiForgeryToken()
    
        @Html.Hidden("SelectedCountryId", Model.CountryId)
        @Html.Hidden("SelectedRaceCourseId", Model.RaceCourseId)
        @*@Html.Hidden("SelectedSeasonId", Model.SeasonId)*@ 
        @Html.Hidden("SelectedSuperMeetTypeId", Model.supermeetingtypeid)
        @Html.Hidden("SelectedSuperRaceTypeId", Model.superracetypeid)
        @Html.Hidden("SelectedNumRunnersId", Model.NumberOfRunners)
    }

        <div class="panel-flip buttons" id="race-flip"><span id="race-span">Show</span> more (FAV/LSW/TF/QN/F4 statistics)</div>
        <div class="panel-history" id="race-history">
            @*@{Html.RenderPartial("_StatsTable", Model.MarketData);}*@
        </div>
    </div>
}